### ISSUE TITLE
[Tracking] Create Plugin Standard

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-code-analysis#45]
This is a tracking issue with a rough idea for [milestone 1](https://github.com/WordPress/wporg-code-analysis/milestone/1). Individual issues can be opened for each of these after there's some more discussion and the idea is refined further.

- [x] start [p2 post to get feedback](https://make.wordpress.org/meta/2021/04/27/automatically-catching-bugs-in-plugins/) on what the standard should be, what metrics should be
- [ ] gather baseline stats
- [ ] collaborate w/ stakeholders to decide on standard
- [x] build rough plugin standard
- [x] show results to PRT so they can give feedback
- [ ] ask for contributors to help build/iterate on sniffs
- [ ] iterate on scanner until it implement the standard w/ low false-positive ratio
- [ ] identify gaps in documentation, and what the docs should recommend. hand off to docs team
- [ ] identify gaps in core (helper functions, etc), and open core tickets
- [ ] evaluate stats after done iterating, see how close that got us to the goal. if didn't reach goal, then try to understand why, through stats + asking for feedback + intuition. continue iterating to fix those problems
