### ISSUE TITLE
[Tracking] Educate Plugin Authors & Users

### ISSUE THREAD

**Issue by iandunn** [WordPress/wporg-code-analysis#46]
This is a tracking issue with a rough idea for [milestone 2](https://github.com/WordPress/wporg-code-analysis/milestone/2). Individual issues can be opened for each of these after there's some more discussion and the idea is refined further.

- [ ] follow up w/ docs team on publishing docs from [milestone 1](https://github.com/WordPress/wporg-code-analysis/issues/45)
- [ ] follow up w/ core team on tickets we opened from [milestone 1](https://github.com/WordPress/wporg-code-analysis/issues/45)
- [ ] show results to new plugins on upload, maybe prevent submission to PRT until all errors fixed?
- [ ] email results to existing plugins after each commit
- [ ] add "badges" to plugin pages indicating that the plugin meets the standard?
- [ ] re-evaluate stats and iterate
